<?php
/**
 * @author Dany <cgh@tom.com>
 * File_Name Common.php
 * Time: 8:08 PM
 */

namespace app\index\controller;


class Common extends \app\common\controller\Common
{
    /**
     * 蚂蚁防红 - 初始化
     *
     * @auth Dany <cgh@tom.com>
     *
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}